name: Cleanup PRs
on:
  pull_request:
    types: [closed]
jobs:
  docs:
    name: Teardown Documentation Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: metadata
        run: |-
          echo "##[set-output name=node-version;]$(cat .node-version)"
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.metadata.outputs.node-version }}
          cache: yarn
      - run: yarn dlx surge teardown dollarsign-pr-${{ github.event.pr_number }} --token ${{ secrets.SURGE_TOKEN }}
