name: Documentation
on:
  push:
    branches:
      - master
jobs:
  docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate JSDoc
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: .
          output_dir: ./docs
          template: minami
          front_page: README.md
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
          publish_dir: ./docs
