name: Documentation
on:
  push:
    branches:
      - master
jobs:
  docs:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: andstor/jsdoc-action@v1
        with:
          source_dir: .
          output_dir: ./docs
          template: minami
          front_page: README.md
      - uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs
