name: Release
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: metadata
        run: |-
          echo "##[set-output name=node-version;]$(cat .node-version)"
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.metadata.outputs.node-version }}
          cache: true
      - id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ hashFiles('yarn.lock') }}
      - run: yarn install
        if: steps.cache.outputs.cache-hit != 'true'
      - run: yarn build
      - run: yarn docs
      - run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
