name: Tests
on:
  push:
    branches-ignore:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: metadata
        run: |-
          echo "##[set-output name=node-version;]$(cat .node-version)"
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.metadata.outputs.node-version }}
          cache: true
      - id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ hashFiles('yarn.lock') }}
      - run: yarn install --check-cache
        if: steps.cache.outputs.cache-hit != 'true'
      - run: yarn lint
      - run: yarn check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: metadata
        run: |-
          echo "##[set-output name=node-version;]$(cat .node-version)"
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.metadata.outputs.node-version }}
          cache: true
      - id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ hashFiles('yarn.lock') }}
      - run: yarn install --check-cache
        if: steps.cache.outputs.cache-hit != 'true'
      - run: yarn test --ci
